def sum(a, b):
    try:
        return a + b
    except Exception as ex:
        print(f"Following error occured: {ex}")

